### ISSUE TITLE
upgrade to 4.6?

### ISSUE THREAD

**Issue by marsh-circle** [futurefirst/capscorrect#5]
Hi Vitor,
Thanks for the Module btw :)
Are you likely to be upgrading this module to work with 4.6?
Martin

**Comment by davidknoll** [comment]
Hi Martin,

I'm afraid that Vitor is no longer working at Future First, and we are no
longer in regular contact regarding this extension. However I did make and
accept some changes last year. As we are having a new system developed and
moving away from CiviCRM, we will not be moving to 4.6 ourselves and it is
unlikely that our public extensions will be officially maintained on work
time. Happy to accept good/useful pull requests though.

Thanks,
Dave

**Comment by davidknoll** [comment]
Just wanted to add, that I hope to still do some Civi stuff in my spare time!

**Comment by davidknoll** [comment]
Closing this due to #6 , should now be compatible.
